### ISSUE TITLE
Installation error: node-gyp and node-inspector

### ISSUE THREAD

**Issue by andybobrov** [codersForFun/react-keystone-boilerplate#6]
**node -v**
8.9.1

**npm -v**
5.5.1

**xcode installed**

### Console output after _npm install_ :
```> v8-debug@0.7.7 preinstall /Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/v8-debug
> node -e 'process.exit(0)'



> v8-profiler@5.6.5 preinstall /Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/v8-profiler
> node -e 'process.exit(0)'


> fsevents@1.1.3 install /Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/fsevents
> node install

[fsevents] Success: "/Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> kerberos@0.0.21 install /Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
../lib/kerberos.cc:97:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("Kerberos").ToLocalChecked(), t->GetFunction());
          ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8.h:3099:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../lib/kerberos.cc:177:25: warning: 'ToInt32' is deprecated [-Wdeprecated-declarations]
  call->flags =info[1]->ToInt32()->Uint32Value();
                        ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8.h:2331:10: note: 'ToInt32' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Int32> ToInt32() const);
         ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
2 warnings generated.
./Release/.deps/Release/obj.target/kerberos/lib/kerberos.o.d.raw Stats {
  dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 3014364,
  size: 1369,
  blocks: 8,
  atimeMs: 1511436480000,
  mtimeMs: 1511436480000,
  ctimeMs: 1511436480000,
  birthtimeMs: 1511436480000,
  atime: 2017-11-23T11:28:00.000Z,
  mtime: 2017-11-23T11:28:00.000Z,
  ctime: 2017-11-23T11:28:00.000Z,
  birthtime: 2017-11-23T11:28:00.000Z }
  CXX(target) Release/obj.target/kerberos/lib/worker.o
./Release/.deps/Release/obj.target/kerberos/lib/worker.o.d.raw Stats {
  dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 3014367,
  size: 1296,
  blocks: 8,
  atimeMs: 1511436481000,
  mtimeMs: 1511436481000,
  ctimeMs: 1511436481000,
  birthtimeMs: 1511436481000,
  atime: 2017-11-23T11:28:01.000Z,
  mtime: 2017-11-23T11:28:01.000Z,
  ctime: 2017-11-23T11:28:01.000Z,
  birthtime: 2017-11-23T11:28:01.000Z }
CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
./Release/.deps/Release/obj.target/kerberos/lib/kerberosgss.o.d.raw Stats {
  dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 3014370,

  size: 109,
  blocks: 8,
  atimeMs: 1511436481000,
  mtimeMs: 1511436481000,
  ctimeMs: 1511436481000,
  birthtimeMs: 1511436481000,
  atime: 2017-11-23T11:28:01.000Z,
  mtime: 2017-11-23T11:28:01.000Z,
  ctime: 2017-11-23T11:28:01.000Z,
  birthtime: 2017-11-23T11:28:01.000Z }
  CC(target) Release/obj.target/kerberos/lib/base64.o
./Release/.deps/Release/obj.target/kerberos/lib/base64.o.d.raw Stats {
  dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 3014373,
  size: 74,
  blocks: 8,
  atimeMs: 1511436482000,
  mtimeMs: 1511436482000,
  ctimeMs: 1511436482000,
  birthtimeMs: 1511436481000,
  atime: 2017-11-23T11:28:02.000Z,
  mtime: 2017-11-23T11:28:02.000Z,
  ctime: 2017-11-23T11:28:02.000Z,
  birthtime: 2017-11-23T11:28:01.000Z }
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
../lib/kerberos_context.cc:15:70: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> obj = Nan::New(constructor_template)->GetFunction()->NewInstance();
/Users/brobobro/.node-gyp/8.9.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../lib/kerberos_context.cc:57:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]

  target->ForceSet(Nan::New<String>("KerberosContext").ToLocalChecked(), t->GetFunction());
          ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8.h:3099:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
2 warnings generated.
./Release/.deps/Release/obj.target/kerberos/lib/kerberos_context.o.d.raw Stats {
  dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 3014379,
  size: 1355,
  blocks: 8,
  atimeMs: 1511436483000,
  mtimeMs: 1511436483000,
  ctimeMs: 1511436483000,
  birthtimeMs: 1511436483000,
  atime: 2017-11-23T11:28:03.000Z,
  mtime: 2017-11-23T11:28:03.000Z,
  ctime: 2017-11-23T11:28:03.000Z,
  birthtime: 2017-11-23T11:28:03.000Z }
  SOLINK_MODULE(target) Release/kerberos.node

> ursa@0.9.4 install /Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/ursa
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
./Release/.deps/Release/obj.target/ursaNative/src/ursaNative.o.d.raw Stats {
  dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 3014399,
  size: 4005,
  blocks: 8,

  atimeMs: 1511436486000,
  mtimeMs: 1511436486000,
  ctimeMs: 1511436486000,
  birthtimeMs: 1511436486000,
  atime: 2017-11-23T11:28:06.000Z,
  mtime: 2017-11-23T11:28:06.000Z,
  ctime: 2017-11-23T11:28:06.000Z,
  birthtime: 2017-11-23T11:28:06.000Z }
  SOLINK_MODULE(target) Release/ursaNative.node

> v8-debug@0.7.7 install /Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@8.9.1 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:38:20: warning: 'Call' is deprecated [-Wdeprecated-declarations]
        v8::Debug::Call(fn);
                   ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8-debug.h:192:3: note: 'Call' has been explicitly marked deprecated here
  V8_DEPRECATED("No longer supported",
  ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/debug.cc:38:27: error: too few arguments to function call, expected at least 2, have 1
        v8::Debug::Call(fn);
        ~~~~~~~~~~~~~~~   ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8-debug.h:193:17: note: 'Call' declared here
                static MaybeLocal<Value> Call(
                ^
../src/debug.cc:46:61: error: too few arguments to function call, single argument 'isolate' was not specified
        Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8-debug.h:209:17: note: 'GetDebugContext' declared here
                static Local<Context> GetDebugContext(Isolate* isolate));
../src/debug.cc:46:45: warning: 'GetDebugContext' is deprecated [-Wdeprecated-declarations]
        Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                            ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8-debug.h:208:3: note: 'GetDebugContext' has been explicitly marked deprecated here
  V8_DEPRECATED("Use v8-inspector",
  ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/debug.cc:48:20: warning: 'SendCommand' is deprecated [-Wdeprecated-declarations]
        v8::Debug::SendCommand(debug_isolate, *command, command.length());
                   ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8-debug.h:169:3: note: 'SendCommand' has been explicitly marked deprecated here
  V8_DEPRECATED("No longer supported",

  ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/debug.cc:61:67: error: too few arguments to function call, single argument 'isolate' was not specified
        Local<Context> debug_context = v8::Debug::GetDebugContext();
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8-debug.h:209:17: note: 'GetDebugContext' declared here
                static Local<Context> GetDebugContext(Isolate* isolate));
                ^
../src/debug.cc:61:51: warning: 'GetDebugContext' is deprecated [-Wdeprecated-declarations]
        Local<Context> debug_context = v8::Debug::GetDebugContext();
                                                  ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8-debug.h:208:3: note: 'GetDebugContext' has been explicitly marked deprecated here
  V8_DEPRECATED("Use v8-inspector",
  ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/debug.cc:65:22: error: no member named 'GetMirror' in 'v8::Debug'
          v8::Debug::GetMirror(info.GetIsolate()->GetCurrentContext(), info[0]);
          ~~~~~~~~~~~^
../src/debug.cc:66:38: warning: 'GetDebugContext' is deprecated [-Wdeprecated-declarations]
          debug_context = v8::Debug::GetDebugContext();
                                     ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8-debug.h:208:3: note: 'GetDebugContext' has been explicitly marked deprecated here
  V8_DEPRECATED("Use v8-inspector",
  ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/debug.cc:66:54: error: too few arguments to function call, single argument 'isolate' was not specified
          debug_context = v8::Debug::GetDebugContext();
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/brobobro/.node-gyp/8.9.1/include/node/v8-debug.h:209:17: note: 'GetDebugContext' declared here
                static Local<Context> GetDebugContext(Isolate* isolate));
                ^
5 warnings and 5 errors generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 16.7.0

gyp ERR! command "/usr/local/Cellar/node/8.9.1/bin/node" "/Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-buil
d" "--module=/Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/v8-debug/build/debug/v0.7.7/node-v57-darwin-x64/debug.node" "--module_name=debug" "--module_path=/
Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/v8-debug/build/debug/v0.7.7/node-v57-darwin-x64"
gyp ERR! cwd /Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/v8-debug
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/8.9.1/bin/node /Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/node-gyp/bin/node-gyp.j
s build --fallback-to-build --module=/Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/v8-debug/build/debug/v0.7.7/node-v57-darwin-x64/debug.node --module_name=d
ebug --module_path=/Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/v8-debug/build/debug/v0.7.7/node-v57-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/8.9.1/bin/node" "/Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-
build"
node-pre-gyp ERR! cwd /Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/v8-debug
node-pre-gyp ERR! node -v v8.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/8.9.1/bin/node /Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --m
odule=/Users/brobobro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/v8-debug/build/debug/v0.7.7/node-v57-darwin-x64/debug.node --module_name=debug --module_path=/Users/brobo
bro/dev/brainfuck/keystone/react-keystone-boilerplate/node_modules/v8-debug/build/debug/v0.7.7/node-v57-darwin-x64' (1)
npm WARN eslint-config-airbnb-base@7.2.0 requires a peer of eslint@^3.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@7.2.0 requires a peer of eslint-plugin-import@^1.16.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brobobro/.npm/_logs/2017-11-23T11_28_12_134Z-debug.log```

**Comment by Davidcreador** [comment]
@andybobrov Hello! I'll check it out. :)
